server:
  port: 50003
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
  application:
    name: authentication-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.160.33:3306/sc_auth?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  security:
    oauth2:
      jwt:
        signingKey: secret
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: true
#        isolation:
#          thread:
#            timeoutInMilliseconds: 30000
#
#ribbon:
#  ReadTimeout: 30000
#  ConnectTimeout: 30000

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
