spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.160.33:3306/sc_auth?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: sm@123456
  #redis config
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

    #开启跟踪总线事件
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

#使用redis存储roken需要设置的参数
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      user-authorization-uri: http://localhost:50003/oauth/authorize  #授权码认证方式需要的
#      access-token-uri: http://localhost:50003/oauth/token  #密码模式需要用到的获取 token 的接口
#    resource:
#      id: client
#      user-info-uri: secret
#    authorization:
#      check-token-access: http://localhost:50003/oauth/check_token

management:
  endpoints:
    web:
      exposure:
        include: '*'
