server:
  port: 50004
spring:
  application:
    name: authorization-server
  redis:
    host: localhost
    port: 6739
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      user-authorization-uri: http://localhost:50003/oauth/authorize  #授权码认证方式需要的
      access-token-uri: http://localhost:50003/oauth/token  #密码模式需要用到的获取 token 的接口
    resource:
      id: client
      user-info-uri: secret
    authorization:
      check-token-access: http://localhost:50003/oauth/check_token