spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.196.160.33:3306/sc_gateway?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: sm@123456
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
        - AddResponseHeader=X-Response-Default-Foo, Default-Bar
        - name: RequestRateLimiter    #名字不能够改变，RequestRateLimiter局部过滤器，使用默认的factory
          args:
            #springcloud gateway不支持mysql等数据库进行背压，目前可以Redis-reactive进行背压
            #每秒允许请求数
            redis-rate-limiter.replenishRate: 2
            #允许并发的请求数[请求宽限的个数]
            redis-rate-limiter.burstCapacity: 10
            rate-limiter: "#{@defaultRedisRateLimiter}"
            #用户唯一身份识别
            key-resolver: "#{@apiKeyResolver}"
    loadbalancer:
      retry:
        enabled: true

  redis:
    host: localhost
    port: 6379

  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456

  rabbitmq:
    host: 139.196.160.33
    port: 5672
    username: admin
    password: admin
    virtual-host: /

jetcache:
  statIntervalMinutes: 1
  areaInCacheName: false
  hidePackages: com.emall.gatewayweb
  local:
    # 默认永久本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
  remote:
    # 默认永久的远程缓存
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

gate:
  ignore:
    authentication:
      startWith: /oauth, /v2/api-docs, /oss

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.springboot.cloud: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB
