server:
  port: 50001
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
spring:
  application:
    name: emall-manageplat
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/MobileBI_DB?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    name: root
    password: 123456
logging:
  level:
    com.springcloud.sm_systemserver: TRACE
    java.sql.PreparedStatement: debug
  path: logs/

  file:
    max-size: 1GB
