CREATE TABLE emall_member (
    id BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) COMMENT '用户名',
    password VARCHAR(255) COMMENT '密码',
    mobile VARCHAR(11) comment '手机号',
    photo BIGINT COMMENT '头像',
    email VARCHAR(255) COMMENT '邮箱',
    nick_name VARCHAR(255) COMMENT '昵称',
    motto VARCHAR(1000) COMMENT '座右铭',
    create_time DATETIME COMMENT '创建时间',
    update_time DATETIME COMMENT '更新时间',
    login_time DATETIME COMMENT '最后登录时间',
    status INT(1) COMMENT '账户状态,0-启用,1-禁用',
    growth_point int comment '成长值',
    level_name VARCHAR(255) COMMENT '会员等级描述',
    free_freight int comment '是否免运费,0-是,1-不是',
    sign_in int comment '是否有签到权,0-是,1-不是',
    point_score int comment '积分',
    wechatId VARCHAR(50) comment '微信id',
	PRIMARY KEY (id)
)  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='会员信息表';
