DROP TABLE IF EXISTS `emall_order`;
CREATE TABLE emall_order (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '订单id',
    username BIGINT NOT NULL COMMENT '会员账号',
    coupon_id BIGINT COMMENT '优惠券id',
    order_no VARCHAR(64) COMMENT '订单编号',
    total_amount DECIMAL(10 , 2 ) COMMENT '订单总金额',
    pay_amount DECIMAL(10 , 2 ) COMMENT '应付金额（实际支付金额）',
    freight_amount DECIMAL(10 , 2 ) COMMENT '运费金额',
    points_amount DECIMAL(10 , 2 ) COMMENT '积分抵扣金额',
    coupon_amount DECIMAL(10 , 2 ) COMMENT '优惠券抵扣金额',
    pay_type INT(1) COMMENT '支付方式：未支付(0)-支付宝(1)-微信(2)-银联(3)',
    source_type INT(1) COMMENT '订单来源：小程序(0)-app订单(1)-PC端(2)',
    order_status INT(1) COMMENT '订单状态：待付款(0)-待发货(1)-已发货(2)-已完成(3)-已关闭(4)-无效订单(5)',
    order_type INT(1) COMMENT '订单类型：0->正常订单；1->秒杀订单',
    delivery_company VARCHAR(64) COMMENT '物流公司(配送方式)',
    delivery_sn VARCHAR(64) COMMENT '物流单号',
    auto_confirm_day INT COMMENT '自动确认时间（天）',
    obtain_points INT COMMENT '可以获得的积分',
    growth_points INT COMMENT '可以活动的成长值',
    promotion_info VARCHAR(100) COMMENT '活动信息',
    bill_type INT(1) COMMENT '发票类型：0->不开发票；1->电子发票；2->纸质发票',
    bill_header VARCHAR(200) COMMENT '发票抬头',
    bill_content VARCHAR(200) COMMENT '发票内容',
    bill_receiver_phone VARCHAR(32) COMMENT '收票人电话',
    bill_receiver_email VARCHAR(64) COMMENT '收票人邮箱',
    receiver_name VARCHAR(100) NOT NULL COMMENT '收货人姓名',
    receiver_phone VARCHAR(32) NOT NULL COMMENT '收货人电话',
    receiver_post_code VARCHAR(32) COMMENT '收货人邮编',
    receiver_province VARCHAR(32) COMMENT '省份/直辖市',
    receiver_city VARCHAR(32) COMMENT '城市',
    receiver_region VARCHAR(32) COMMENT '区',
    receiver_detail_address VARCHAR(200) COMMENT '详细地址',
    note VARCHAR(500) COMMENT '订单备注',
    confirm_status INT(1) COMMENT '确认收货状态：0->未确认；1->已确认',
    delete_status INT(1) NOT NULL DEFAULT 0 COMMENT '删除状态：0->未删除；1->已删除',
    use_points INT COMMENT '下单时使用的积分',
    payment_time DATETIME COMMENT '支付时间',
    delivery_time DATETIME COMMENT '发货时间',
    receive_time DATETIME COMMENT '确认收货时间',
    comment_time DATETIME COMMENT '评价时间',
    created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
    created_by VARCHAR(20) NOT NULL COMMENT '创建人',
    updated_by VARCHAR(20) NOT NULL COMMENT '更新人',
    PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COMMENT='订单抬头信息';


DROP TABLE IF EXISTS `emall_order_item`;
create table emall_order_item
(
   id                   bigint not null auto_increment,
   order_id             bigint comment '订单id',
   order_no             varchar(64) comment '订单编号',
   product_id           bigint comment '商品id',
   product_pic          varchar(500) comment '商品图片',
   product_name         varchar(200) comment '商品名称',
   product_brand        varchar(200) comment '商品品牌',
   product_no           varchar(64) comment '商品条码',
   product_price        decimal(10,2) comment '销售价格',
   product_quantity     int comment '购买数量',
   product_sku_id       bigint comment '商品sku编号',
   product_sku_code     varchar(50) comment '商品sku条码',
   product_category_id  bigint comment '商品分类id',
   promotion_name       varchar(200) comment '商品促销名称',
   promotion_amount     decimal(10,2) comment '商品促销分解金额',
   coupon_amount        decimal(10,2) comment '优惠券优惠分解金额',
   integration_amount   decimal(10,2) comment '积分优惠分解金额',
   real_amount          decimal(10,2) comment '该商品经过优惠后的分解金额',
   gift_integration     int not null default 0 comment '商品赠送积分',
   gift_growth          int not null default 0 comment '商品赠送成长值',
   specification        varchar(500) comment '商品规格属性',
   created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
   updated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
   created_by VARCHAR(20) NOT NULL COMMENT '创建人',
   updated_by VARCHAR(20) NOT NULL COMMENT '更新人',
   primary key (id)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COMMENT='订单详细信息';